// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using AccessControlPro.Infrastructure.Persistence;

#nullable disable

namespace AccessControlPro.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260303100000_AddPhoneUniqueIndex")]
partial class AddPhoneUniqueIndex
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
}
